Using mozilla build system
---
1) Check out the sources into the extensions folder of an existing tree.
2) Enable in your mozconfig using --enable-extensions, e.g. like so:
	ac_add_options --enable-extensions=default,mintrayr
3) Build. The output will go into $objdir/dist/xpi-stage